# Generated by Django 5.2.4 on 2025-07-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_restaurant_couverture_restaurant_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='est_disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='specialite',
            field=models.CharField(choices=[('africain', 'Africain'), ('europeen', 'Européen'), ('asiatique', 'Asiatique')], default='africain', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='ville',
            field=models.CharField(choices=[('abomey', 'Abomey'), ('abomey-calavi', 'Abomey-Calavi'), ('adjohoun', 'Adjohoun'), ('adja-ouèrè', 'Adja-Ouèrè'), ('agbangnizoun', 'Agbangnizoun'), ('aguégués', 'Aguégués'), ('akpro-missérété', 'Akpro-Missérété'), ('allada', 'Allada'), ('alohoun', 'Alohoun'), ('athiémé', 'Athiémé'), ('avrankou', 'Avrankou'), ('banikoara', 'Banikoara'), ('bantè', 'Bantè'), ('bassila', 'Bassila'), ('bembèrèkè', 'Bembèrèkè'), ('bétérou', 'Bétérou'), ('bopa', 'Bopa'), ('boukoumbé', 'Boukoumbé'), ('come', 'Comè'), ('cotonou', 'Cotonou'), ('covè', 'Covè'), ('dangbo', 'Dangbo'), ('dassa-zoumè', 'Dassa-Zoumè'), ('djidja', 'Djidja'), ('dogbo', 'Dogbo'), ('djakotomey', 'Djakotomey'), ('glazoué', 'Glazoué'), ('grand-popo', 'Grand-Popo'), ('ifangni', 'Ifangni'), ('kandi', 'Kandi'), ('karimama', 'Karimama'), ('kétou', 'Kétou'), ('klouékanmè', 'Klouékanmè'), ('kouandé', 'Kouandé'), ('lokossa', 'Lokossa'), ('malanville', 'Malanville'), ('matéri', 'Matéri'), ('natitingou', 'Natitingou'), ('ndali', 'Ndali'), ('nikki', 'Nikki'), ('ouèssè', 'Ouèssè'), ('ouidah', 'Ouidah'), ('parakou', 'Parakou'), ('péhunco', 'Péhunco'), ('perere', 'Pèrèrè'), ('pobè', 'Pobè'), ('portonovo', 'Porto-Novo'), ('sakété', 'Sakété'), ('savalou', 'Savalou'), ('savè', 'Savè'), ('sègbanè', 'Sègbanè'), ('sèmè-podji', 'Sèmè-Podji'), ('sinendé', 'Sinendé'), ('sô-ava', 'Sô-Ava'), ('tchaourou', 'Tchaourou'), ('tanguiéta', 'Tanguiéta'), ('toviklin', 'Toviklin'), ('toucountouna', 'Toucountouna'), ('zakpota', 'Zakpota'), ('zagnanado', 'Zagnanado'), ('zakpota', 'Zakpota'), ('za-kpota', 'Za-Kpota'), ('zè', 'Zè'), ('zogbodomey', 'Zogbodomey'), ('zè', 'Zè'), ('za-kpota', 'Za-Kpota'), ('bembèrèkè', 'Bembèrèkè'), ('bantè', 'Bantè'), ('cana', 'Cana'), ('kpomassè', 'Kpomassè'), ('kétou', 'Kétou'), ('ouinhi', 'Ouinhi'), ('torri-bossito', 'Torri-Bossito'), ('zagnanado', 'Zagnanado'), ('akpro-missérété', 'Akpro-Missérété'), ('bétérou', 'Bétérou'), ('pèrèrè', 'Pèrèrè')], default='cotonou', max_length=100),
        ),
    ]
